//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Debt()
        {
            this.DebtBill = new HashSet<DebtBill>();
            this.Payment = new HashSet<Payment>();
            this.StatementDetail = new HashSet<StatementDetail>();
        }
    
        public int Id { get; set; }
        public System.DateTime DebtDate { get; set; }
        public decimal GrossValue { get; set; }
        public decimal IvaValue { get; set; }
        public decimal DebtTotal { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual User UserId { get; set; }
        public virtual Establishment EstablishmentId { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebtBill> DebtBill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatementDetail> StatementDetail { get; set; }
    }
}
