//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//|
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<ModuleForm> ModuleForms { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Certificate> CertificateSet { get; set; }
        public virtual DbSet<Paremeter> Paremeters { get; set; }
        public virtual DbSet<RolFormPermission> RolFormPermissionSet { get; set; }
        public virtual DbSet<Establishment> Establishments { get; set; }
        public virtual DbSet<TypeEstablishment> TypeEstablishments { get; set; }
        public virtual DbSet<Debt> Debts { get; set; }
        public virtual DbSet<Rent> Contracts { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<DebtBill> DebtBills { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<RolUser> RolUsers { get; set; }
        public virtual DbSet<Statement> Statements { get; set; }
        public virtual DbSet<Calculation> Calculations { get; set; }
        public virtual DbSet<StatementDetail> StatementDetailSet { get; set; }
        public virtual DbSet<Person> PersonSet { get; set; }
        public virtual DbSet<Company> Companys { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
    }
}
