//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatementDetail
    {
        public int Id { get; set; }
        public string Catogory { get; set; }
        public string ItemName { get; set; }
        public string Amount { get; set; }
        public string Period { get; set; }
        public string PreviousPeriodAmount { get; set; }
        public string TargetAmount { get; set; }
        public string Variance { get; set; }
        public string VariancePercentage { get; set; }
        public string CreatedAt { get; set; }
    
        public virtual Statement StatementId { get; set; }
        public virtual Payment PaymentId { get; set; }
        public virtual Debt DebtId { get; set; }
        public virtual Establishment EstablishmentId { get; set; }
        public virtual Rent RentId { get; set; }
    }
}
