//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public string TableName { get; set; }
        public string PropietyName { get; set; }
        public string Action { get; set; }
        public string TimeStamp { get; set; }
        public string UserId { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
    }
}
